### ISSUE TITLE
Add the functionality for conflict error code generation in case of a email address redundancy

### ISSUE THREAD

**Issue by vrangr1** [CSCI-GA-2820-FA22-003/customers#10]
**As a** Developer
**I need** a conflict error code to be generated when a customer tries to register with an email id already in use
**So that** there are no redundant customer accounts with the same email ID.

 ### Assumptions
- REST API for create exists. So, when URL `POST /customers` is used for customer registration, this functionality should be triggered.

### Acceptance Criteria
 ```gherkin
 Given a request to register a new customer
 When an email address is used that is already in use
 Then HTTP 409 Conflict error code should be generated and returned
 ```

**Comment by TestSubjector** [comment]
Perhaps add the `enhancement` label to this issue?

**Comment by mm12063** [comment]
Should the URL be something other than /customers? This function should be used within the POST /customers to check whether the email address already belongs to a customer. Maybe something like /customers/email which would return a boolean if the address already exits in the persistent memory..?
