### ISSUE TITLE
Containers for Local Deployment

### ISSUE THREAD

**Issue by adityakiwi** [CSCI-GA-2820-FA22-003/customers#13]
**As a** Developer
**I need** the containers environment set up 
**So that** the developers can use them in their local environments. 

 ### Assumptions
- Be able to set up the containers
- Have local environments set up. 

### Acceptance Criteria
 ```gherkin
Given I have the containers
When I create the instance and have it set up. 
Then I should be able to push the containers to GitHub to be used on the local machines. 
 ```

**Comment by mm12063** [comment]
Duplicate issue #1
