### ISSUE TITLE
Set up database

### ISSUE THREAD

**Issue by adityakiwi** [CSCI-GA-2820-FA22-003/customers#14]
**As a** Developer
**I need** the database setup
**So that** the state can be maintained in terms of storing all the user data. 

 ### Assumptions
- Ability to leverage database to be able to store and retrieve users. 
- We have an agreed-upon schema

### Acceptance Criteria
 ```gherkin
Given I have the user data collected
When I create the database to store that specified data. 
Then I should be able to use the database to persist the data. 
 ```

**Comment by adityakiwi** [comment]
Want to know what service our database will be using

**Comment by mm12063** [comment]
Specifics on db TBC by Professor.
