### ISSUE TITLE
Implement Github notifications on Slack

### ISSUE THREAD

**Issue by TestSubjector** [CSCI-GA-2820-FA22-003/customers#2]
**As a** Developer
**I need** to use the Slack bot to send GitHub notifications to Slack
**So that** I and my team members can quickly keep track of the most recent changes to the project.

 ### Assumptions
- Understanding of how the Slack GitHub bot works
- Permission to integrate the Slack bot with the GitHub project

### Acceptance Criteria
 ```gherkin
 Given GitHub notification are enabled in the Slack channel
 When an update to an issue or PR occurs for the project
 Then a notification should be sent to the Slack channel with the details of the update
 ```

**Comment by KaterinPerdom** [comment]
This issue should go in progress, have you already started working on it? 
@TestSubjector

**Comment by TestSubjector** [comment]
@KaterinPerdom Technically almost all the groundwork has been done. However, we'll mark it `in progress` and `complete` once the Sprint 1 begins, for convenience sake, as we aren't supposed to do any actual implementation before that.
