### ISSUE TITLE
Implement function to create a customer resource

### ISSUE THREAD

**Issue by TestSubjector** [CSCI-GA-2820-FA22-003/customers#3]
**As a** Developer
**I need** a function that can create a customer object for the eCommerce web site
**So that** I can store the details associated with the new customer.

 ### Assumptions
- Development environment is setup
- Knowledge of Python
- Access to Database schema

### Acceptance Criteria
 ```gherkin
 Given a request to add a new customer
 When the create function is invoked
 Then the database is updated with details of the new customer
 ```

**Comment by mm12063** [comment]
Duplicate of #6
