### ISSUE TITLE
Add /health endpoint to the service for health check on Kubernetes

### ISSUE THREAD

**Issue by vrangr1** [CSCI-GA-2820-FA22-003/customers#54]
**As a** Developer
**I need** a URI to navigate to
**So that** K8s is able to easily check the 'health' status of the service

 ### Assumptions
- Kubernetes Cluster is setup on IBM Cloud
- If the service is running, then return OK 200 

### Acceptance Criteria
 ```gherkin
 Given there is a Kubernetes cluster 
 When the endpoint /health is called
 Then then an HTTP 200 status code is returned
 ```

**Comment by mm12063** [comment]
Update later with correct error code
