### ISSUE TITLE
Add a Github Actions CI badge to the README.md file

### ISSUE THREAD

**Issue by vrangr1** [CSCI-GA-2820-FA22-003/customers#58]
**As a** Developer
**I need** a github actions CI badge in the README.md file
**So that** I can know if the build is broken by checking that

 ### Assumptions
- Continuous Integration is setup.

### Acceptance Criteria
 ```gherkin
 Given a repository
 When a pull request has been merged into the master branch and the build fails
 Then that should be reflected in the github actions CI badge in the README.md file
 ```

**Comment by TestSubjector** [comment]
Issue resolved by Pull Request #62
