### ISSUE TITLE
Enhance the UI to Query a Customer by City

### ISSUE THREAD

**Issue by vrangr1** [CSCI-GA-2820-FA22-003/customers#80]
**As a** Product Owner
**I need** to be able to search for customers by City
**So that** I can get the customers' details based on their city 

 ### Assumptions
- Selenium is used to conduct UI testing.
- The UI has a search input box

### Acceptance Criteria
 ```gherkin
 Given the service is running and a City has been typed into the UI search input box
 When the Search button is clicked
 Then I should get a list of customer records which have the same City
 ```

**Comment by mm12063** [comment]
We need to split this in to 4 different issues: query firstname, lastname, email, city
