### ISSUE TITLE
Enhance the UI to Activate / Deactivate a customer

### ISSUE THREAD

**Issue by vrangr1** [CSCI-GA-2820-FA22-003/customers#81]
**As a** Product Owner
**I need** the ability to be able to activate / deactivate a customer through the UI
**So that** I can activate / deactivate a customer account as per need.

 ### Assumptions
- Selenium is used to conduct UI testing

### Acceptance Criteria
 ```gherkin
 Given the service is running and the customer ID has been entered into the UI
 When the activate / deactivate button is clicked
 Then the customer should activated / deactivated in the database depending on its current status
 ```

**Comment by mm12063** [comment]
This had to be included in branch ui_to_UPDATE_customer__85 as I couldn't update the customers other details without passing the acc_active value too.
